-- =====================================================================
-- YieldShield — Predictive Crop Yield Intelligence System
-- Binalonan, Pangasinan
-- Schema DDL — PostgreSQL 13+
-- =====================================================================
-- Run this as the database owner (yieldshield_owner) against a
-- dedicated database, e.g.:
--     createdb -O yieldshield_owner yieldshield
--     psql "dbname=yieldshield sslmode=require" -f 01_schema.sql
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- 0. Schema + extensions
-- ---------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS yieldshield;
SET search_path TO yieldshield, pg_catalog;

-- Needed for gen_random_uuid() (report file references) and
-- for the encryption helpers used by the security script.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------
-- 1. SEASON
-- ---------------------------------------------------------------------
CREATE TABLE yieldshield.season (
    season_id     INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    season_code   VARCHAR(20)  NOT NULL UNIQUE,      -- e.g. 'DS 2020-2021', 'WS 2017'
    season_label  VARCHAR(60)  NOT NULL,              -- e.g. 'Dry Season 2020-2021'
    season_type   VARCHAR(2)   NOT NULL CHECK (season_type IN ('DS','WS')),
    start_year    SMALLINT     NOT NULL CHECK (start_year BETWEEN 1990 AND 2100),
    end_year      SMALLINT     NOT NULL CHECK (end_year   BETWEEN 1990 AND 2100),
    CONSTRAINT season_year_order CHECK (end_year >= start_year)
);
COMMENT ON TABLE yieldshield.season IS 'Cropping seasons (Dry/Wet) tracked by the system.';

-- ---------------------------------------------------------------------
-- 2. CROP_TYPE
-- ---------------------------------------------------------------------
CREATE TABLE yieldshield.crop_type (
    crop_type_id  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    crop_name     VARCHAR(50) NOT NULL,
    variety       VARCHAR(80),
    -- NULLS NOT DISTINCT (PG15+) is required here: with a plain UNIQUE
    -- constraint, Postgres treats NULL <> NULL, so two rows with the
    -- same crop_name and a NULL variety would NOT violate uniqueness
    -- and ON CONFLICT upserts would silently insert duplicates instead
    -- of updating (verified during ETL testing).
    UNIQUE NULLS NOT DISTINCT (crop_name, variety)
);

-- ---------------------------------------------------------------------
-- 3. BARANGAY
-- ---------------------------------------------------------------------
CREATE TABLE yieldshield.barangay (
    barangay_id         INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    barangay_name       VARCHAR(80) NOT NULL UNIQUE,
    soil_type           VARCHAR(80),
    terrain_type        VARCHAR(60),
    elevation_m_asl     NUMERIC(6,1),
    nearest_water_body  VARCHAR(80),
    land_size_ha        NUMERIC(10,2) CHECK (land_size_ha >= 0),
    irrigation_priority VARCHAR(30)
);

-- ---------------------------------------------------------------------
-- 4. USER_ACCOUNT
-- ---------------------------------------------------------------------
CREATE TABLE yieldshield.user_account (
    user_id        INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    full_name      VARCHAR(120) NOT NULL,
    role           VARCHAR(30)  NOT NULL
                     CHECK (role IN ('Admin','Agricultural Technician','Farmer','Analyst')),
    username       VARCHAR(50)  NOT NULL UNIQUE,
    -- Store ONLY a password hash (bcrypt/argon2id) computed by the
    -- application layer. The database never sees or stores plaintext.
    password_hash  TEXT NOT NULL,
    contact_info   VARCHAR(120),
    date_registered TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_active      BOOLEAN NOT NULL DEFAULT TRUE
);
COMMENT ON COLUMN yieldshield.user_account.password_hash IS
  'bcrypt/argon2id hash generated by the application. Never store or accept plaintext passwords here.';

-- ---------------------------------------------------------------------
-- 5. CLIMATE_RECORD
-- ---------------------------------------------------------------------
CREATE TABLE yieldshield.climate_record (
    climate_id           INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    season_id            INTEGER NOT NULL REFERENCES yieldshield.season(season_id)
                            ON UPDATE CASCADE ON DELETE RESTRICT,
    year                 SMALLINT NOT NULL,
    month                VARCHAR(15) NOT NULL,
    month_no             SMALLINT NOT NULL CHECK (month_no BETWEEN 1 AND 12),
    rainfall_mm_day      NUMERIC(8,2),
    avg_temp_c           NUMERIC(5,2),
    min_temp_c           NUMERIC(5,2),
    max_temp_c           NUMERIC(5,2),
    humidity_pct         NUMERIC(5,2),
    surface_pressure_kpa NUMERIC(6,2),
    solar_rad_mj_m2      NUMERIC(6,2),
    climate_type         VARCHAR(80),
    climate_season       VARCHAR(30),
    latitude             NUMERIC(9,6),
    longitude            NUMERIC(9,6),
    UNIQUE (season_id, year, month_no)
);
CREATE INDEX idx_climate_record_year_month ON yieldshield.climate_record(year, month_no);

-- ---------------------------------------------------------------------
-- 6. PLANTING_TECHNIQUE
-- ---------------------------------------------------------------------
CREATE TABLE yieldshield.planting_technique (
    technique_id          INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    barangay_id           INTEGER NOT NULL REFERENCES yieldshield.barangay(barangay_id)
                             ON UPDATE CASCADE ON DELETE CASCADE,
    crop_type_id          INTEGER NOT NULL REFERENCES yieldshield.crop_type(crop_type_id)
                             ON UPDATE CASCADE ON DELETE CASCADE,
    -- NULL = general/season-independent technique (e.g. the summary
    -- derived from the aggregate Central Data sheet). 'DS' or 'WS' =
    -- a season-specific technique from the detailed reference sheet.
    -- Both can exist side by side for the same barangay+crop.
    season_type           VARCHAR(2) CHECK (season_type IN ('DS','WS')),
    primary_planting_method VARCHAR(255),
    tillage_method        TEXT,
    water_management      TEXT,
    seed_depth_cm         NUMERIC(5,2),
    row_spacing           TEXT,
    seed_rate_kg_ha       NUMERIC(7,2),
    land_prep_method      TEXT,
    special_consideration TEXT,
    UNIQUE NULLS NOT DISTINCT (barangay_id, crop_type_id, season_type)
);

-- ---------------------------------------------------------------------
-- 7. FARM_PROFILE
-- ---------------------------------------------------------------------
CREATE TABLE yieldshield.farm_profile (
    farm_id        INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id        INTEGER NOT NULL REFERENCES yieldshield.user_account(user_id)
                     ON UPDATE CASCADE ON DELETE CASCADE,
    barangay_id    INTEGER NOT NULL REFERENCES yieldshield.barangay(barangay_id)
                     ON UPDATE CASCADE ON DELETE RESTRICT,
    crop_type_id   INTEGER NOT NULL REFERENCES yieldshield.crop_type(crop_type_id)
                     ON UPDATE CASCADE ON DELETE RESTRICT,
    land_area_ha   NUMERIC(10,2) CHECK (land_area_ha >= 0),
    soil_condition VARCHAR(120),
    date_created   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_farm_profile_user ON yieldshield.farm_profile(user_id);
CREATE INDEX idx_farm_profile_barangay ON yieldshield.farm_profile(barangay_id);

-- ---------------------------------------------------------------------
-- 8. PRODUCTION_RECORD  (municipal/historical dataset + farm submissions)
-- ---------------------------------------------------------------------
CREATE TABLE yieldshield.production_record (
    production_id      INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    barangay_id        INTEGER NOT NULL REFERENCES yieldshield.barangay(barangay_id)
                          ON UPDATE CASCADE ON DELETE RESTRICT,
    crop_type_id       INTEGER NOT NULL REFERENCES yieldshield.crop_type(crop_type_id)
                          ON UPDATE CASCADE ON DELETE RESTRICT,
    season_id          INTEGER NOT NULL REFERENCES yieldshield.season(season_id)
                          ON UPDATE CASCADE ON DELETE RESTRICT,
    climate_id         INTEGER REFERENCES yieldshield.climate_record(climate_id)
                          ON UPDATE CASCADE ON DELETE SET NULL,
    -- NULL farm_id = aggregate municipal/barangay-level record (e.g. historical dataset).
    -- Non-null farm_id = a specific farmer's submitted record.
    farm_id            INTEGER REFERENCES yieldshield.farm_profile(farm_id)
                          ON UPDATE CASCADE ON DELETE SET NULL,
    year               SMALLINT NOT NULL,
    month              VARCHAR(15) NOT NULL,
    phase              VARCHAR(10) NOT NULL CHECK (phase IN ('Planting','Harvest')),
    irrigated_area_ha      NUMERIC(10,2),
    rainfed_area_ha        NUMERIC(10,2),
    total_area_planted_ha  NUMERIC(10,2),
    area_harvested_ha      NUMERIC(10,2),
    production_mt          NUMERIC(12,2),
    yield_mt_ha            NUMERIC(8,3)
);
CREATE INDEX idx_production_barangay ON yieldshield.production_record(barangay_id);
CREATE INDEX idx_production_crop ON yieldshield.production_record(crop_type_id);
CREATE INDEX idx_production_season ON yieldshield.production_record(season_id);
CREATE INDEX idx_production_farm ON yieldshield.production_record(farm_id);
CREATE INDEX idx_production_year ON yieldshield.production_record(year);
-- One aggregate (municipal/barangay-level, farm_id IS NULL) record per
-- barangay+crop+season+phase — lets the ETL script safely upsert
-- instead of creating duplicates on re-runs. Farmer-submitted rows
-- (farm_id NOT NULL) are unrestricted by this index.
CREATE UNIQUE INDEX idx_production_unique_aggregate
    ON yieldshield.production_record(barangay_id, crop_type_id, season_id, phase)
    WHERE farm_id IS NULL;

-- ---------------------------------------------------------------------
-- 8b. CROP_FEATURES — engineered features for model training, one row
--     per barangay+crop+season (built from the Planting-phase record,
--     the planting-month climate, and the resulting yield outcome).
--     Descriptive attributes (soil type, technique text, etc.) are
--     deliberately NOT duplicated here — join back to barangay /
--     planting_technique for those. This table only holds the keys
--     plus the numeric features actually engineered for modeling.
-- ---------------------------------------------------------------------
CREATE TABLE yieldshield.crop_features (
    feature_id            INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    barangay_id            INTEGER NOT NULL REFERENCES yieldshield.barangay(barangay_id)
                              ON UPDATE CASCADE ON DELETE CASCADE,
    crop_type_id           INTEGER NOT NULL REFERENCES yieldshield.crop_type(crop_type_id)
                              ON UPDATE CASCADE ON DELETE CASCADE,
    season_id              INTEGER NOT NULL REFERENCES yieldshield.season(season_id)
                              ON UPDATE CASCADE ON DELETE CASCADE,
    climate_id             INTEGER REFERENCES yieldshield.climate_record(climate_id)
                              ON UPDATE CASCADE ON DELETE SET NULL,
    -- traceability back to the specific Planting-phase production row
    -- this feature set was engineered from
    production_id          INTEGER REFERENCES yieldshield.production_record(production_id)
                              ON UPDATE CASCADE ON DELETE SET NULL,
    planting_month         VARCHAR(15) NOT NULL,
    planting_year          SMALLINT NOT NULL,
    total_area_planted_ha  NUMERIC(10,2),
    irrigated_area_ha      NUMERIC(10,2),
    rainfed_area_ha        NUMERIC(10,2),
    yield_mt_ha            NUMERIC(8,3) NOT NULL,
    yield_imputed           BOOLEAN NOT NULL DEFAULT FALSE,
    irrigated_ratio         NUMERIC(10,4),
    rainfed_ratio           NUMERIC(10,4),
    water_availability      NUMERIC(10,4),
    temperature_range       NUMERIC(6,2),
    heat_stress_index       NUMERIC(10,4),
    humidity_temp_interaction NUMERIC(12,4),
    solar_temp_interaction    NUMERIC(12,4),
    date_generated          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (barangay_id, crop_type_id, season_id)
);
CREATE INDEX idx_crop_features_barangay ON yieldshield.crop_features(barangay_id);
CREATE INDEX idx_crop_features_crop ON yieldshield.crop_features(crop_type_id);
CREATE INDEX idx_crop_features_season ON yieldshield.crop_features(season_id);
COMMENT ON TABLE yieldshield.crop_features IS
  'Engineered feature set (one row per barangay+crop+season) for training/serving predictive_model. Descriptive attributes live in barangay/planting_technique — join, don''t duplicate.';

-- ---------------------------------------------------------------------
-- 9. PREDICTIVE_MODEL
-- ---------------------------------------------------------------------
CREATE TABLE yieldshield.predictive_model (
    model_id      INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    model_name    VARCHAR(100) NOT NULL,
    algorithm     VARCHAR(60)  NOT NULL,
    mae           NUMERIC(10,4),
    mse           NUMERIC(12,4),
    r_squared     NUMERIC(6,4),
    trained_date  TIMESTAMPTZ,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE
);

-- ---------------------------------------------------------------------
-- 10. FARM_INPUT_LOG
-- ---------------------------------------------------------------------
CREATE TABLE yieldshield.farm_input_log (
    input_log_id            INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    farm_id                  INTEGER NOT NULL REFERENCES yieldshield.farm_profile(farm_id)
                                ON UPDATE CASCADE ON DELETE CASCADE,
    technique_id             INTEGER REFERENCES yieldshield.planting_technique(technique_id)
                                ON UPDATE CASCADE ON DELETE SET NULL,
    seeding_rate_kg_ha       NUMERIC(7,2),
    plant_density_hills_per_ha INTEGER,
    seedlings_per_hill       INTEGER,
    land_area_ha             NUMERIC(10,2),
    rainfall_input           NUMERIC(8,2),
    temperature_input        NUMERIC(5,2),
    planting_date            DATE,
    date_logged               TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_input_log_farm ON yieldshield.farm_input_log(farm_id);

-- ---------------------------------------------------------------------
-- 11. CROP_RECOMMENDATION
-- ---------------------------------------------------------------------
CREATE TABLE yieldshield.crop_recommendation (
    recommendation_id  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    input_log_id       INTEGER NOT NULL REFERENCES yieldshield.farm_input_log(input_log_id)
                          ON UPDATE CASCADE ON DELETE CASCADE,
    crop_type_id       INTEGER NOT NULL REFERENCES yieldshield.crop_type(crop_type_id)
                          ON UPDATE CASCADE ON DELETE RESTRICT,
    suitability_level  VARCHAR(20) CHECK (suitability_level IN ('High','Moderate','Low','Not Recommended')),
    rationale          TEXT,
    date_generated     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_crop_reco_input_log ON yieldshield.crop_recommendation(input_log_id);

-- ---------------------------------------------------------------------
-- 12. YIELD_PREDICTION
-- ---------------------------------------------------------------------
CREATE TABLE yieldshield.yield_prediction (
    prediction_id            INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    input_log_id             INTEGER NOT NULL REFERENCES yieldshield.farm_input_log(input_log_id)
                                ON UPDATE CASCADE ON DELETE CASCADE,
    model_id                 INTEGER NOT NULL REFERENCES yieldshield.predictive_model(model_id)
                                ON UPDATE CASCADE ON DELETE RESTRICT,
    predicted_yield_mt_ha     NUMERIC(8,3),
    predicted_production_mt  NUMERIC(12,2),
    date_generated            TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_yield_pred_input_log ON yieldshield.yield_prediction(input_log_id);
CREATE INDEX idx_yield_pred_model ON yieldshield.yield_prediction(model_id);

-- ---------------------------------------------------------------------
-- 13. REPORT
-- ---------------------------------------------------------------------
CREATE TABLE yieldshield.report (
    report_id       INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    prediction_id   INTEGER NOT NULL REFERENCES yieldshield.yield_prediction(prediction_id)
                      ON UPDATE CASCADE ON DELETE CASCADE,
    generated_by    INTEGER REFERENCES yieldshield.user_account(user_id)
                      ON UPDATE CASCADE ON DELETE SET NULL,
    report_type     VARCHAR(50),
    date_generated  TIMESTAMPTZ NOT NULL DEFAULT now(),
    file_path       TEXT
);

-- ---------------------------------------------------------------------
-- 14. SUS_RESPONSE  (System Usability Scale survey — 10 Likert items)
-- ---------------------------------------------------------------------
CREATE TABLE yieldshield.sus_response (
    response_id    INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id        INTEGER NOT NULL REFERENCES yieldshield.user_account(user_id)
                     ON UPDATE CASCADE ON DELETE CASCADE,
    item_1  SMALLINT CHECK (item_1  BETWEEN 1 AND 5),
    item_2  SMALLINT CHECK (item_2  BETWEEN 1 AND 5),
    item_3  SMALLINT CHECK (item_3  BETWEEN 1 AND 5),
    item_4  SMALLINT CHECK (item_4  BETWEEN 1 AND 5),
    item_5  SMALLINT CHECK (item_5  BETWEEN 1 AND 5),
    item_6  SMALLINT CHECK (item_6  BETWEEN 1 AND 5),
    item_7  SMALLINT CHECK (item_7  BETWEEN 1 AND 5),
    item_8  SMALLINT CHECK (item_8  BETWEEN 1 AND 5),
    item_9  SMALLINT CHECK (item_9  BETWEEN 1 AND 5),
    item_10 SMALLINT CHECK (item_10 BETWEEN 1 AND 5),
    sus_score      NUMERIC(5,2),
    date_submitted TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_sus_response_user ON yieldshield.sus_response(user_id);

-- ---------------------------------------------------------------------
-- 15. SUPPORT_REQUEST
-- ---------------------------------------------------------------------
CREATE TABLE yieldshield.support_request (
    request_id     INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id        INTEGER NOT NULL REFERENCES yieldshield.user_account(user_id)
                     ON UPDATE CASCADE ON DELETE CASCADE,
    request_type   VARCHAR(60),
    description    TEXT,
    status         VARCHAR(20) NOT NULL DEFAULT 'Open'
                     CHECK (status IN ('Open','In Progress','Resolved','Closed')),
    date_submitted TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_support_request_user ON yieldshield.support_request(user_id);

-- ---------------------------------------------------------------------
-- 16. Lightweight audit trail for sensitive tables
-- ---------------------------------------------------------------------
CREATE TABLE yieldshield.audit_log (
    audit_id     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    table_name   VARCHAR(60) NOT NULL,
    row_pk       TEXT NOT NULL,
    action       VARCHAR(10) NOT NULL CHECK (action IN ('INSERT','UPDATE','DELETE')),
    changed_by   TEXT NOT NULL DEFAULT current_user,
    changed_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    old_data     JSONB,
    new_data     JSONB
);

CREATE OR REPLACE FUNCTION yieldshield.fn_audit_trigger() RETURNS TRIGGER AS $$
DECLARE
    pk_val TEXT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        pk_val := (row_to_json(OLD)::jsonb ->> TG_ARGV[0]);
        INSERT INTO yieldshield.audit_log(table_name, row_pk, action, old_data)
        VALUES (TG_TABLE_NAME, pk_val, TG_OP, row_to_json(OLD)::jsonb);
        RETURN OLD;
    ELSIF TG_OP = 'UPDATE' THEN
        pk_val := (row_to_json(NEW)::jsonb ->> TG_ARGV[0]);
        INSERT INTO yieldshield.audit_log(table_name, row_pk, action, old_data, new_data)
        VALUES (TG_TABLE_NAME, pk_val, TG_OP, row_to_json(OLD)::jsonb, row_to_json(NEW)::jsonb);
        RETURN NEW;
    ELSE
        pk_val := (row_to_json(NEW)::jsonb ->> TG_ARGV[0]);
        INSERT INTO yieldshield.audit_log(table_name, row_pk, action, new_data)
        VALUES (TG_TABLE_NAME, pk_val, TG_OP, row_to_json(NEW)::jsonb);
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = yieldshield, pg_catalog;

-- Track changes on the accounts and farm data that matter most for accountability.
CREATE TRIGGER trg_audit_user_account
    AFTER INSERT OR UPDATE OR DELETE ON yieldshield.user_account
    FOR EACH ROW EXECUTE FUNCTION yieldshield.fn_audit_trigger('user_id');

CREATE TRIGGER trg_audit_farm_profile
    AFTER INSERT OR UPDATE OR DELETE ON yieldshield.farm_profile
    FOR EACH ROW EXECUTE FUNCTION yieldshield.fn_audit_trigger('farm_id');

CREATE TRIGGER trg_audit_production_record
    AFTER INSERT OR UPDATE OR DELETE ON yieldshield.production_record
    FOR EACH ROW EXECUTE FUNCTION yieldshield.fn_audit_trigger('production_id');

COMMIT;
