-- =====================================================================
-- YieldShield — flag auto-generated care-schedule tasks
-- Run AFTER 21_seed_distribution.sql, as yieldshield_owner.
--
-- Editing a cropping's planting date or planting technique used to
-- leave its auto-generated care schedule (crop_task rows plotted by
-- farm_calendar.py's generate_activities() when the cropping was
-- first submitted) anchored to the OLD planting date — Calendar.tsx
-- and the Dashboard's "What to do this week" (WeekPlan.tsx), which
-- both just read crop_task as-is, would keep showing due dates
-- computed from a planting date the farmer had already changed.
--
-- Fixing that means being able to safely delete-and-recreate the
-- schedule on such an edit (see routers/farm_input.py's
-- update_farm_input) — but crop_task also holds tasks a farmer added
-- by hand from the Calendar (routers/tasks.py's create_task), and
-- those must never be silently wiped out by an unrelated edit. There
-- was no column distinguishing the two, so this adds one.
--
-- Backfill note: every *existing* row is marked auto_generated = TRUE.
-- This app has no live production data yet (see INTEGRATION_NOTES.md)
-- and the schema has offered no other way to add a task until
-- recently, so the overwhelming majority of any existing rows are the
-- seeded schedule, not hand-added ones — treating them all as
-- auto-generated is the correct default here. A real deployment with
-- a meaningful population of hand-added tasks predating this
-- migration would want a more careful backfill.
-- =====================================================================
BEGIN;
SET search_path TO yieldshield, pg_catalog;

ALTER TABLE yieldshield.crop_task
    ADD COLUMN IF NOT EXISTS auto_generated BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE yieldshield.crop_task SET auto_generated = TRUE;

COMMENT ON COLUMN yieldshield.crop_task.auto_generated IS
  'TRUE for rows plotted by farm_calendar.py''s generate_activities() at cropping submission time or regenerated by update_farm_input() on a planting-date/technique edit. FALSE (the default) for anything a farmer added by hand from Calendar.tsx. Only TRUE, not-yet-done rows are ever deleted/recreated by an edit — hand-added tasks are never touched.';

COMMIT;
