import hashlib
import secrets
from datetime import datetime, timedelta, timezone

import jwt
from passlib.context import CryptContext

from .config import settings

# bcrypt matches the column comment in 01_schema.sql
# ("bcrypt/argon2id hash generated by the application").
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")


def hash_password(plain: str) -> str:
    return pwd_context.hash(plain)


def verify_password(plain: str, hashed: str) -> bool:
    try:
        return pwd_context.verify(plain, hashed)
    except ValueError:
        # Malformed hash in the DB — never let this crash the request,
        # just treat it as a failed verification.
        return False


# ---------------------------------------------------------------------
# Session tokens (JWT) — carries user_id + role so every subsequent
# request can set the RLS session vars without a DB round trip.
# ---------------------------------------------------------------------
def create_session_token(user_id: int, role: str, username: str, admin_role: str | None = None) -> str:
    now = datetime.now(timezone.utc)
    payload = {
        "sub": str(user_id),
        "role": role,
        "username": username,
        "admin_role": admin_role,
        "iat": now,
        "exp": now + timedelta(minutes=settings.JWT_EXPIRE_MINUTES),
    }
    return jwt.encode(payload, settings.JWT_SECRET, algorithm=settings.JWT_ALGORITHM)


def decode_session_token(token: str) -> dict:
    return jwt.decode(token, settings.JWT_SECRET, algorithms=[settings.JWT_ALGORITHM])


# ---------------------------------------------------------------------
# Password reset tokens — the raw token goes in the emailed link only;
# the DB only ever stores sha256(raw token).
# ---------------------------------------------------------------------
def generate_reset_token() -> tuple[str, str]:
    """Returns (raw_token_for_email_link, sha256_hash_for_db)."""
    raw = secrets.token_urlsafe(32)
    digest = hashlib.sha256(raw.encode("utf-8")).hexdigest()
    return raw, digest


def hash_reset_token(raw: str) -> str:
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()
